export const FETCH_ISSUES = 'FETCH_ISSUES';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAIL = 'FETCH_ISSUES_FAIL';
export const UPDATE_ISSUES_ORDER = 'UPDATE_ISSUES_ORDER';
export const UPDATE_ISSUES_SUCCESS = 'UPDATE_ISSUES_SUCCESS';

export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAIL = 'FETCH_REPOS_FAIL';

export const SET_SELECTED_REPO = 'SET_SELECTED_REPO';
export const SET_API_KEY = 'SET_API_KEY';